import './globals.scss';
import Providers from '@/components/provider';

export const metadata = {
  title: 'Tomoca Website',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="custom-body-font custom-heading-font">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
